### PR TITLE
fire and partial light updates

### PR DESCRIPTION
**Pull request by khalidakh**
- i saw nadine use ('c1 s s end') for dragon, so i made most units use that. units with good skill damage favored it, while units that dont have good skill damage prefer to stay in dragon for the full duration
- coabilities slightly focusing on spamming shapeshift with how good mars is
- kleimann is a better SS on most
- some optimizations to go along with the above changes

- updated "meta" light units except H!elly since her spiral update is coming soon

### CODE REVIEW

**Comment by Mushymato** [comment]
Nadine ('c1 s s end') was a mistake, characters are required to do at least c3 s for chart purposes.

**Comment by khalidakh** [comment]
> Nadine ('c1 s s end') was a mistake, characters are required to do at least c3 s for chart purposes.

should that be the case for the purposes of the sim even though mars can use skill even before the c1 connects? 

https://www.youtube.com/watch?v=4rutcT6JC1U

**Comment by khalidakh** [comment]
removed the c1 s s end

**Comment by Mushymato** [comment]
hm the c3 s thing is about time spent in dragon, so 's s' would parse to 's c3 c3 s' and be fine.

**Pull request merged**
